### PR TITLE
php8.3 support

### PR DESCRIPTION
**Pull request by faissaloux**

### CODE REVIEW

**Review by ProjektGopher — APPROVED** [review]
Thx man. I'll version and release this later tonight

**Comment by faissaloux** [comment]
Sure!

Did you run the tests before merging this to main! I was waiting for the result before merging it.

It is failing on the main branch, and I think to fix this we shouldn't push the `composer.lock` file.

What do you think?

**Comment by ProjektGopher** [comment]
I think you're right - I hadn't waited, I thought it had already run. I'm wondering now if my compiling the binary using 8.3 deps that'll create issues when someone is using 8.2/8.1 on their system

**Comment by faissaloux** [comment]
I don't think this would be a problem since the conflict exists only in dev dependencies.

**Comment by ProjektGopher** [comment]
Good point. Yeah I think adding the lock file to our gitignore and removing the file from the repo sounds like the right move

**Pull request merged**
