### PR TITLE
Build windows

### PR DESCRIPTION
**Pull request by gpibarra**
Resolve https://github.com/ProjektGopher/whisky/issues/56

### CODE REVIEW

**Comment by gpibarra** [comment]
Tested ok.
PS: Don't forget to enable the `sodium` extension or run `php whiskey app:build whiskey -v` to see any errors.

**Comment by ProjektGopher** [comment]
@gpibarra Do you feel like there's value in _us_ enforcing this by possibly adding a `check-extensions` hidden command and amending our `composer build` command to call that first? `php whisky check-extensions && php whisky app:build`

**Comment by gpibarra** [comment]
> @gpibarra Do you feel like there's value in _us_ enforcing this by possibly adding a `check-extensions` hidden command and amending our `composer build` command to call that first? `php whisky check-extensions && php whisky app:build`

In my opinion, I think not, I think it is a dependency of the box package (via laravel zero), the box dependency is not installed by composer (if installed with composer, the `sodium` extension is required), instead instead, the box phar is located at "./vendor/laravel-zero/framework/bin/box" and as it says in the laravel zero documentation, https://laravel-zero.com/docs/build- a-standalone-application#debug-information recommend using `-v` for when it fails.
I think that with a simple warning in the documentation it reaches, also, in "https://github.com/ProjektGopher/whisky#contributing" it says that we do not make builds in the collaborations, with which it would not be necessary for the collaborators that use windows have to do builds

**Comment by ProjektGopher** [comment]
I should probably change that line in the docs slightly. I want to avoid people committing a compiled binary, but I can definitely see the utility in people building it while testing locally

**Review by ProjektGopher — APPROVED** [review]

**Pull request merged**
